name: nouveautrad
favicon: null
layout_spectrum: 0.3374885742086917
typography_spectrum: 0.972477767849341
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.09586706827394664
  lightness: 0.8426055600866675
  saturation: 0.6798699691426009
  rhythmicContrast: 0.2316874957177788
purpose: []
